### ISSUE TITLE
不能正常进行go get操作，错误如下文图中描述

### ISSUE THREAD

**Issue by foxhack** [rencalo770/gengine#1]
环境
golang  go 1.14.1
GOPROXY=https://goproxy.cn
GOSUMDB=off
操作系统：windown 10.0.18363 暂缺 Build 18363
![image](https://user-images.githubusercontent.com/16910405/86533690-6183f100-bf05-11ea-937c-9c5692222eec.png)

**Comment by rencalo770** [comment]
感谢您的反馈。这其实是个路径设定的问题：
在go.mod文件中这样写就行了。
![image](https://user-images.githubusercontent.com/58161376/86535737-2093d880-bf15-11ea-988a-9f26461c7146.png)

我这两天把路径统一调整为github.com/rencalo770/gengine的形式，以此让大家可以以类似其他github模块的引用方式，来引用此模块。处理完毕了，我会再来comment一下。
再次表示感谢！

**Comment by rencalo770** [comment]
抱歉，上面表述稍微有点问题。
你可以直接把项目clone到任意目录下即可。然后使用go.mod这样写:
![WeChatWorkScreenshot_70c1a575-824c-49d0-8fb0-35c0cc15a022](https://user-images.githubusercontent.com/58161376/86591490-41673700-bfc4-11ea-90c7-9204e02984e8.png)
