### ISSUE TITLE
建议弄个最佳实践。针对没接触过和想用的人。

### ISSUE THREAD

**Issue by excxapp** [rencalo770/gengine#11]
ps:此为建议，非BUG反馈。

对于一个新出来的东西，可能有一些人特别是像我们这种刚开始接触用的人，
一看一脸懵逼，不知道咋用。
建议增加一个使用案例，各种方式实践的，这对于入门使用感觉还是很重要的。

当然这是在你们实践允许的情况下弄。

往往好的例子，让新手入门简单可能对拓广面比较有帮助吧。
同时，可否建立个交流群，一起讨论使用啥的也好

谢谢

**Comment by rencalo770** [comment]
感谢您的关注和支持！

在REAME中，我们已经附上了中、英版使用文档，以及设计时的想法，重要的API在中英文文档中均有列述，以及部分特殊API还会在每个章节的开头，都会说一下背景，并且在章节末附上了对应测试的位置。如果有任何使用问题，我们会在24小时之内答复您。

不过你说也的确实是个问题：因为文档中绝大部分只说API怎么使用和简单的单元测试，但却没有给出一个非常完整的使用的业务场景，毕竟想把不同的业务场景细节摸透，确实是一件很费功夫的事情，如果有相关的交流群，确实能帮助使用者少走很多弯路。

然后，今天新建的交流群
gengine官方QQ群号:1132683357

**Comment by yongliu1992** [comment]
> 1132683357

@rencalo770  qq群号是不是错误了

**Comment by rencalo770** [comment]
你好，经确认，无误的：
![QQ](https://user-images.githubusercontent.com/58161376/92341044-18ac0c80-f0ef-11ea-9022-d74054861f50.jpeg)

**Comment by yongliu1992** [comment]
确实没办法搜到，我还找了其他同事试了试，您这个是不是讨论组 或者设置了什么隐私保护。
可以把我拉进群吗？ 575710047


| |
liuyong
|
|
a3831524@126.com
|
签名由网易邮箱大师定制


在2020年09月7日 09:47，rencalo770<notifications@github.com> 写道：

你好，经确认，无误的：

**Comment by yongliu1992** [comment]
会不会是这个原因



| |
liuyong
|
|
a3831524@126.com
|
签名由网易邮箱大师定制


在2020年09月8日 17:01，liuyong<a3831524@126.com> 写道：
确实没办法搜到，我还找了其他同事试了试，您这个是不是讨论组 或者设置了什么隐私保护。
可以把我拉进群吗？ 575710047


| |
liuyong
|
|
a3831524@126.com
|
签名由网易邮箱大师定制


在2020年09月7日 09:47，rencalo770<notifications@github.com> 写道：

你好，经确认，无误的：

**Comment by rencalo770** [comment]
非常抱歉，我刚才在手机上重新查看了群设置，发现新建的群是默认是开启“不让搜索”，再次表示非常的抱歉！

现在已经可以搜索加入，或者直接扫readme上的二维码加入了

**Comment by yongliu1992** [comment]
没事 没事。


| |
liuyong
|
|
a3831524@126.com
|
签名由网易邮箱大师定制


在2020年09月8日 22:25，rencalo770<notifications@github.com> 写道：

非常抱歉，我刚才在手机上重新查看了群设置，发现新建的群是默认是开启“不让搜索”，再次表示非常的抱歉！

现在已经可以搜索加入
