### ISSUE TITLE
有个小bug，engine执行那里有个闭包问题

### ISSUE THREAD

**Issue by a120209520** [rencalo770/gengine#14]
engine/gengine.go  ExecuteConcurrent函数    r变量闭包了，应该用rr
`eMsg = append(eMsg, fmt.Sprintf("rule: \"%s\" executed, error:\n %+v ", r.RuleName, e))`

其他几个模式，带有并发的都有这个bug，可以修改下～

**Comment by rencalo770** [comment]
你好，感谢您的反馈！
你用的是哪个版本呢？我看最新代码里面都是rr，不是r呢。

**Comment by rencalo770** [comment]
非常感谢您的反馈，你说的没错！

你说的很对，日志这里确实有点小问题，还好不是主逻辑。
-----
再次表示感谢。另外，希望大佬可以加入gengine使用交流QQ群号:1132683357 
我们只要看到问题反馈，会在最短的时间内修复处理。

**Comment by rencalo770** [comment]
已经修复这个日志问题，已经发布了新版本v1.3.6

非常感谢您的反馈！

**Comment by a120209520** [comment]
修复速度惊人！
