### ISSUE TITLE
not a issue, it is a sugguestion

### ISSUE THREAD

**Issue by hellocowboy** [rencalo770/gengine#15]
You may need to make a BSD licence file for your framework "gengine" to make everyone use it without worry. not only just a BSD label.

**Comment by rencalo770** [comment]
Thanks for your reminder.
The target we open the source  of gengine, because we hope our job could help or improve other people's job and business!

**Comment by rencalo770** [comment]
I have added the BSD licence file into the project!
--------
thanks for your suggestion!
