### ISSUE TITLE
咨询一下

### ISSUE THREAD

**Issue by shiftwinting** [rencalo770/gengine#2]
B 站新一代 golang 规则引擎的设计与实现

这个文章是否撤掉？
是的，有没有地方可以看到。

**Comment by rencalo770** [comment]
感谢关注，这片文章发布之后，反响非常好。
但因为我忘了走公司流程报备，依据公司规定，暂时被我隐藏了。
目前正在走文章发布、和gengine开源的报备流程。
流程也快走完了，这几天我会在infoQ上重新发布一下，然后就能看到了。

**Comment by shiftwinting** [comment]
好的，谢谢
