### ISSUE TITLE
We need the support of building rules from JSON

### ISSUE THREAD

**Issue by nekohor** [rencalo770/gengine#4]
We need the support of building rules from JSON

**Comment by rencalo770** [comment]
what does your rule look like?

gengine's rule looks like this:
`
rule "rule-name" "rule-description" salience 10
begin

// your logic here
// math calculate 
// logic operation
// API call
end
`

**Comment by nekohor** [comment]
Business people can use diagram editor, g6-editor for example, to communicate with rule engine from front-end webpage, which helps business people to specify the rules themselves.

**Comment by rencalo770** [comment]
rule is just string, json can be translate to string, so json can be translate rule.

in our company. we edit rule(string)  on  front-end webpage, and then send the rule(string) to  rule engine in back-end.

i think, you just need translate your users' grammar(json or any other format) to the rule(string) grammar that fit for the rule engine.

**Comment by liouxiao** [comment]
Maybe a JSON dialect can be defined for the rule spec, just like 

https://github.com/hyperjumptech/grule-rule-engine/pull/72/files

For example:

```
type GengineJSON struct {
 	Name                  string        `json:"name"`
 	Description         string        `json:"desc"`
 	Salience              int           `json:"salience"`
 	Expressions        []interface{} `json:"expressions"`
}
```

But how to organize the `begin` - `end` section to expressions would still be a question.

**Comment by rencalo770** [comment]
you are smart and clever！

you have two ways:
one is  that you can  make "begin" and "end"  as default, "begin"  and "end"will not be handled until you execute the rule! 
the other way is that you can design your struct looks like this:

type GengineJSON struct {
	Name                  string        `json:"name"`
	Description         string        `json:"desc"`
	Salience              int           `json:"salience"`
	Begin                string         `json:"begin"`
	Expressions        []interface{} `json:"expressions"`
	End                string         `json:"end"`
}
