### ISSUE TITLE
module declares its path as: gengine  but was required as: github.com/rencalo770/gengine

### ISSUE THREAD

**Issue by nekohor** [rencalo770/gengine#5]
output =>
=====================================================
go: test imports
        github.com/rencalo770/gengine/base: github.com/rencalo770/gengine@v1.1.7: parsing go.mod:
        module declares its path as: gengine
                but was required as: github.com/rencalo770/gengine
=====================================================

go mod  =>
module test
go 1.15

require(
    gengine v1.0.8
)

replace gengine => github.com/rencalo770/gengine v1.1.5

**Comment by rencalo770** [comment]
you may create a test project in a wrong way, here i give you an example  that build a project by  go mod:

your project structure should look like this:

test
|- go.mod
|– main.go


1. choose a dir  run this command:
 A. "mkdir test"
 B. "go mod init test"
in project dir  "test", there will be a file "go.mod"

2. edit go.mod,  if you JUST ONLY denpend on gengine, your go.mod should be looks like this:
----------------------
module test

go 1.13

require gengine v1.0.8

replace gengine => github.com/rencalo770/gengine v1.1.7
-----------------------

if you NOT ONLY denpend on gengine, and you alse denpend on grpc framework,  your go.mod should be looks like this:
-------------------
module test

go 1.13

require (
      gengine v1.0.8
     google.golang.org/grpc v1.22.0
)

replace gengine => github.com/rencalo770/gengine v1.1.7
-----------------


3. creat a file main.go  in project "test", your main file should look like this:
----------------
package main

import (
	"fmt"
	"gengine/base"
	"gengine/builder"
	"gengine/context"
	"gengine/engine"
)

const rule  = `
rule "rule-name" "rule-des" salience  10
begin
println("hello world")
end
`


func main() {
	dataContext := context.NewDataContext()
	//rename and inject
	dataContext.Add("println",fmt.Println)

	//init rule engine
	knowledgeContext := base.NewKnowledgeContext()
	ruleBuilder := builder.NewRuleBuilder(knowledgeContext, dataContext)

	e1 := ruleBuilder.BuildRuleFromString(rule)
	if e1 != nil {
		panic("build rule error")
	}
	eng := engine.NewGengine()
	e2 := eng.Execute(ruleBuilder, true)

	if e2 != nil {
		panic("execute rule error")
	}
}
----------------

4.  execute "main.go", get result:
![企业微信截图_bf89fb2e-182b-4c99-9b5e-bf021523a486](https://user-images.githubusercontent.com/58161376/90646126-66a8bf80-e269-11ea-94ed-6e86515903c0.png)
