### ISSUE TITLE
 Evaluate MapVarValue Only support directly-Pointer-Map, directly-Pointer-Slice and directly-Pointer-Array  or Map, Slice and Array in Pointer-Struct

### ISSUE THREAD

**Issue by nekohor** [rencalo770/gengine#6]
```

    type MapTypeWithKeyStr  map[string]int
    type MapTypeWithKeyInt  map[int]string



   //define
    type MS struct {
	    MII *map[int]int
	    MSI MapTypeWithKeyStr
	    MIS MapTypeWithKeyInt  
    }
```
```
    
    //init
	MS := &MS{
		MII: &map[int]int{1: 1},
		MSI: MapTypeWithKeyStr{"hello": 1},
		MIS: MapTypeWithKeyInt {1: "hello"},
	}
```

**Comment by rencalo770** [comment]
yes, golang‘s feature decides it!  if programmer write it right it,  When users configure rules, they are unaware of this.

there is an example  in golang :
```golang
type Person struct {
      Age int
}

// it is not a ptr, when you call this func to change Person's Age, you will  change nothing!
func (p Person)SetAge( a int){
     p.Age = a
}


```

**Comment by nekohor** [comment]
What you mean is that the barren programming language Golang lead to the compromise of user who have to use struct signature and method to wrap the abstraction of business.

**Comment by rencalo770** [comment]
in some conditions, almost what it means.
but you  can not only use struct ,but  also you can directly inject functions or data without struct to do what you want，such as follow example:
![WeChatWorkScreenshot_a40719c3-894b-4180-aa2e-441c311a8b3a](https://user-images.githubusercontent.com/58161376/90761647-4a169100-e316-11ea-816b-0f18c10c79bf.png)

**Comment by nekohor** [comment]
Aoligei
