### ISSUE TITLE
你好，试用了你的规则引擎，发现map[string]int 的情况下。。无法做运算吗？

### ISSUE THREAD

**Issue by menjiasong00** [rencalo770/gengine#9]
map[string]int 的情况下。。无法做运算吗？intMap["test"]= 1 可以执行，intMap["test"]= 1+1 执行报错：reflect: call of reflect.Value.Int on float64 Value、可并不是 float64啊

**Comment by rencalo770** [comment]
你好，非常感谢您的issue！你提的这个的确是个bug,我们已经修复了这个bug，我们已经发了一个新的tag版本 v1.2.1。感谢您能继续使用。

另外，如果你不介意的话，可以留下你的支付宝账号(最好是发送邮件告知我们，邮箱地址在readme中)，我们给你发个小红包，以表示对您的感谢！

**Comment by menjiasong00** [comment]
非常感谢修复bug。对golang生态之前一个像样的引擎都没有来说， 这个规则引擎对我们来说有很大的意义。感谢你们开源和贡献。红包就不需要了。我会继续研究和使用它并且一起完善

**Comment by menjiasong00** [comment]
非常感谢你们能修复bug。对golang生态之前一个像样的引擎都没有来说， 这个规则引擎对我们来说有很大的意义。感谢你们开源和贡献。红包就不需要了。我会继续研究和使用它并且一起完善&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rencalo770/gengine"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 晚上6:00
收件人:&nbsp;"rencalo770/gengine"<gengine@noreply.github.com&gt;;
抄送:&nbsp;"杺の纞"<526762400@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rencalo770/gengine] 你好，试用了你的规则引擎，发现map[string]int 的情况下。。无法做运算吗？ (#9)





 
你好，非常感谢您的issue！你提的这个的确是个bug,我们已经修复了这个bug，我们已经发了一个新的tag版本 v1.2.1。感谢您能继续使用。
 
另外，如果你不介意的话，可以留下你的支付宝账号(最好是发送邮件告知我们，邮箱地址在readme中)，我们给你发个小红包，以表示对您的感谢！

**Comment by rencalo770** [comment]
再次向您表示衷心地感谢！
